// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207033028_InitialFullSeeder")]
    partial class InitialFullSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Backend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuanganId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuanganId");

                    b.HasIndex("UserId");

                    b.ToTable("Peminjamans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RuanganId = 1,
                            Status = "Approved",
                            TanggalPinjam = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalSelesai = new DateTime(2024, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gedung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ruangans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gedung = "D4",
                            IsDeleted = false,
                            Kapasitas = 30,
                            Nama = "C.102"
                        },
                        new
                        {
                            Id = 2,
                            Gedung = "D3",
                            IsDeleted = false,
                            Kapasitas = 40,
                            Nama = "HH.201"
                        },
                        new
                        {
                            Id = 3,
                            Gedung = "Pasca Sarjana",
                            IsDeleted = false,
                            Kapasitas = 20,
                            Nama = "PS.2.10"
                        },
                        new
                        {
                            Id = 4,
                            Gedung = "SAW",
                            IsDeleted = false,
                            Kapasitas = 15,
                            Nama = "SAW.10.11"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Nama = "Admin",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "yere@example.com",
                            Nama = "Yere",
                            Password = "yere123",
                            Role = "Mahasiswa"
                        });
                });

            modelBuilder.Entity("Backend.Models.Peminjaman", b =>
                {
                    b.HasOne("Backend.Models.Ruangan", "Ruangan")
                        .WithMany()
                        .HasForeignKey("RuanganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruangan");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
